// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC26tTlAFbpUm9td_Wwku8bO_jjpz8-1dE',
    appId: '1:316188704946:web:f28c59df3f262651d3c9ab',
    messagingSenderId: '316188704946',
    projectId: 'chat-appame',
    authDomain: 'chat-appame.firebaseapp.com',
    storageBucket: 'chat-appame.appspot.com',
    measurementId: 'G-NDX0M4G1K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_m0svZiifJz5QVoMPWpnRp-yEwejAmE',
    appId: '1:316188704946:android:fcf0aaabe6864e24d3c9ab',
    messagingSenderId: '316188704946',
    projectId: 'chat-appame',
    storageBucket: 'chat-appame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEOT7O-bs5jblA5rtkeFWVxCZJTkIiG1I',
    appId: '1:316188704946:ios:cb38f134238ff415d3c9ab',
    messagingSenderId: '316188704946',
    projectId: 'chat-appame',
    storageBucket: 'chat-appame.appspot.com',
    iosBundleId: 'com.example.chatAppame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEOT7O-bs5jblA5rtkeFWVxCZJTkIiG1I',
    appId: '1:316188704946:ios:cb38f134238ff415d3c9ab',
    messagingSenderId: '316188704946',
    projectId: 'chat-appame',
    storageBucket: 'chat-appame.appspot.com',
    iosBundleId: 'com.example.chatAppame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC26tTlAFbpUm9td_Wwku8bO_jjpz8-1dE',
    appId: '1:316188704946:web:2251f62ab6570027d3c9ab',
    messagingSenderId: '316188704946',
    projectId: 'chat-appame',
    authDomain: 'chat-appame.firebaseapp.com',
    storageBucket: 'chat-appame.appspot.com',
    measurementId: 'G-WW12S8YQXR',
  );
}
